Web_DienThoaiDiDong_1/Web_DienThoaiDiDong_1/MvcApplication8/Areas/Admin/Controllers/QuanlisanphamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcApplication8.Models;
using System.IO;
namespace MvcApplication8.Areas.Admin.Controllers
{
    
    public class QuanlisanphamController : Controller
    {
        //
        // GET: /Admin/Quanlisanpham/
        DienThoaiDiDong1Entities1 db = new DienThoaiDiDong1Entities1();
        public ActionResult Index()
        {
            return View(db.sanphams.Where(n=>n.moi==1).ToList());
        }
        public ActionResult Dienthoai()
        {
            return View(db.sanphams.Where(n=>n.style == 0).ToList());
        }
        public ActionResult Phukien()
        {
            return View(db.sanphams.Where(n => n.style == 1).ToList());
        }

        #region //thêm mới sản phẩm

        [HttpGet] //tạo trang để thêm
            //tạo action Themmoi
        public ActionResult Themmoi()
        {
            //đưa dữ liệu vào dropdownlist
            ViewBag.theloai_id = new SelectList(db.theloaisps.ToList(),"theloai_id","theloai_name");
            return View();
        }
        //pt này load ảnh + post dữ liệu lên
        [HttpPost]
        //[ValidateInput(false)]  //thuộc tính 
           
        public ActionResult Themmoi(sanpham sp, HttpPostedFileBase UrlAnh)
        {

            ViewBag.theloai_id = new SelectList(db.theloaisps.ToList(), "theloai_id", "theloai_name");
            //kiểm tra đường dẫn ảnh bìa
            if (UrlAnh == null)
            {
                ViewBag.Thongbao = "Chọn hình ảnh";
                return View();
            }

          //thêm vào cơ sở dữ liệu
            //kiểm tra sự tồn tại bên csdl

            if (ModelState.IsValid)
            {
                //lưu tên file
                var fileName = Path.GetFileName(UrlAnh.FileName);
                //lưu đường dẫn
                var path = Path.Combine(Server.MapPath("~/Hinhanh/hinhanhsp"), fileName);
                //kiểm tra hình ảnh đã tồn tại hay chưa
                if (System.IO.File.Exists(path))
                {
                    ViewBag.Thongbao = "Hình ảnh đã tồn tại";
                }
                else
                {
                    UrlAnh.SaveAs(path);
                }
                sp.hinhanh_sp = UrlAnh.FileName;
                db.sanphams.Add(sp);
                db.SaveChanges();
            }

            return View();
        }
        #endregion

        #region  //chỉnh sửa sản phẩm
        [HttpGet]
        public ActionResult Edit(int id)
        {
            sanpham sp = db.sanphams.SingleOrDefault(n => n.sanpham_id == id);
            if (sp == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            ViewBag.theloai_id = new SelectList(db.theloaisps.ToList(), "theloai_id", "theloai_name",sp.theloai_id);
            return View(sp);
        }

        [HttpPost]
        //[ValidateInput(false)]  //thuộc tính 
        public ActionResult Edit(sanpham sp)
        {
            //c1: tạo đối tượng
            //sanpham sp1 = db.sanphams.SingleOrDefault(n => n.sanpham_id = sp.sanpham_id);
            //sp1.sanpham_name = sp.sanpham_name;
            //db.SaveChanges();

            //c2:
            if (ModelState.IsValid)
            {
                
                //thực hiện cập nhật trong model
                db.Entry(sp).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }

            ViewBag.theloai_id = new SelectList(db.theloaisps.ToList(), "theloai_id", "theloai_name",sp.theloai_id);

            return RedirectToAction("Index");





        }

        #endregion

        #region//hiển thị chi tiết sản phẩm

        public ActionResult Details(int id)
        {
            sanpham sp = db.sanphams.SingleOrDefault(n => n.sanpham_id == id);
            if (sp == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            ViewBag.theloai_id = new SelectList(db.theloaisps.ToList(), "theloai_id", "theloai_name", sp.theloai_id);
            return View(sp);
        }
        #endregion

        #region//Xóa sản phẩm
        [HttpGet]
        public ActionResult Delete(int id)
        {
            sanpham sp = db.sanphams.SingleOrDefault(n => n.sanpham_id == id);
            if (sp == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(sp);
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult Xacnhanxoa(int id)
        {
            sanpham sp = db.sanphams.SingleOrDefault(n => n.sanpham_id == id);
            if (sp == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            db.sanphams.Remove(sp);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        #endregion










    }
}

Web_DienThoaiDiDong_1/Web_DienThoaiDiDong_1/MvcApplication8/Controllers/Phụ kiện/PhukienController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcApplication8.Controllers.Phụ_kiện
{
    public class PhukienController : Controller
    {
        //
        // GET: /Phukien/

        public ActionResult Index()
        {
            return View();
        }

    }
}

Web_DienThoaiDiDong_1/Web_DienThoaiDiDong_1/MvcApplication8/Areas/Admin/Views/Quanlisanpham/Delete.cshtml
@model MvcApplication8.Models.sanpham

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Layout/LayoutAdmin.cshtml";
}

<h2>Delete</h2>

<h3>Bạn có muốn xóa hay không?</h3>
<fieldset>
    <legend>sanpham</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.sanpham_id)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.sanpham_id)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.sanpham_name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.sanpham_name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.gia_sanpham)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.gia_sanpham)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.soluong_sp)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.soluong_sp)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.theloai_id)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.theloai_id)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.hinhanh_sp)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.hinhanh_sp)
    </div>

    @*<div class="display-label">
         @Html.DisplayNameFor(model => model.hinhanh_sp1)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.hinhanh_sp1)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.hinhanh_sp3)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.hinhanh_sp3)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.hinhanh_sp4)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.hinhanh_sp4)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.kichthuoc_hinhanh)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.kichthuoc_hinhanh)
    </div>*@

    <div class="display-label">
         @Html.DisplayNameFor(model => model.camera_truoc)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.camera_truoc)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.camera_sau)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.camera_sau)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.he_dieu_hanh)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.he_dieu_hanh)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.cpu)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.cpu)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ram)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ram)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.bo_nho_trong)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.bo_nho_trong)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.the_nho)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.the_nho)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.sim)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.sim)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ket_noi)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ket_noi)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.pin)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.pin)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.chuthich)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.chuthich)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.moi)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.moi)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.style)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.style)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <br />
        <input style="color:blue" type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}
<style>
    .display-label {
        float: left;
    }

    .display-field {
        margin-left: 100px;
        color: blue;
    }

    a {
        color: red;
    }

        a:hover {
            color: blue;
        }
</style>

Web_DienThoaiDiDong_1/Web_DienThoaiDiDong_1/MvcApplication8/Areas/Admin/Views/Quanlisanpham/Details.cshtml
@model MvcApplication8.Models.sanpham

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Layout/LayoutAdmin.cshtml";
}

<h2>Details</h2>

<fieldset>
    <legend>sanpham</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.sanpham_id)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.sanpham_id)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.sanpham_name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.sanpham_name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.gia_sanpham)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.gia_sanpham)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.soluong_sp)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.soluong_sp)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.theloaisp.theloai_name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.theloai_id)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.hinhanh_sp)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.hinhanh_sp)
    </div>

    @*<div class="display-label">
         @Html.DisplayNameFor(model => model.hinhanh_sp1)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.hinhanh_sp1)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.hinhanh_sp3)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.hinhanh_sp3)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.hinhanh_sp4)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.hinhanh_sp4)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.kichthuoc_hinhanh)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.kichthuoc_hinhanh)
    </div>*@

    <div class="display-label">
         @Html.DisplayNameFor(model => model.camera_truoc)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.camera_truoc)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.camera_sau)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.camera_sau)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.he_dieu_hanh)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.he_dieu_hanh)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.cpu)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.cpu)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ram)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ram)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.bo_nho_trong)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.bo_nho_trong)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.the_nho)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.the_nho)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.sim)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.sim)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ket_noi)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ket_noi)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.pin)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.pin)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.chuthich)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.chuthich)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.moi)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.moi)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.style)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.style)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.sanpham_id }) |
    @Html.ActionLink("Delete", "Delete", new { id = Model.sanpham_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>
<style>
    .display-label {
         float:left;

    } 
    .display-field {
       margin-left:100px;
       color:blue;
    }
    a {
        color: red;
    }
    a:hover{
        color:blue;
    }
</style>

Web_DienThoaiDiDong_1/Web_DienThoaiDiDong_1/MvcApplication8/Areas/Admin/Views/Quanlisanpham/Dienthoai.cshtml
@model IEnumerable<MvcApplication8.Models.sanpham>

@{
    ViewBag.Title = "Dienthoai";
    Layout = "~/Areas/Admin/Views/Layout/LayoutAdmin.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading" style="text-align:center;font-weight:bold">
                Danh sách điện thoại
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="dataTable_wrapper">
                    @Html.ActionLink("Thêm mới", "Themmoi")
                    <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>     
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.sanpham_id)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.hinhanh_sp)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.sanpham_name)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.gia_sanpham)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.soluong_sp)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.theloai_id)
                                </th>

                                <th>
                                    @Html.DisplayNameFor(model => model.camera_truoc)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.camera_sau)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.he_dieu_hanh)
                                </th>
                                @*<th>
                                    @Html.DisplayNameFor(model => model.cpu)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.ram)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.bo_nho_trong)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.the_nho)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.sim)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.ket_noi)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.pin)
                                </th>*@
                                <th>
                                    @Html.DisplayNameFor(model => model.moi)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.style)
                                </th>
                                <th>Chức năng</th>
                            </tr>
                        </thead>
                        <tbody>
                             @foreach (var item in Model)
                            {
                                <tr class="odd gradeX">
                                   
                                    <td>
                                        @Html.DisplayFor(modelItem => item.sanpham_id)
                                    </td>
                                    <td>
                                        <img style="height:50px;width:50px" src="~/Hinhanh/hinhanhsp/@item.hinhanh_sp" />

                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.sanpham_name)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.gia_sanpham)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.soluong_sp)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.theloai_id)
                                    </td>                                 

                                    <td>
                                        @Html.DisplayFor(modelItem => item.camera_truoc)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.camera_sau)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.he_dieu_hanh)
                                    </td>
                                    @*<td>
                                        @Html.DisplayFor(modelItem => item.cpu)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.ram)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.bo_nho_trong)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.the_nho)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.sim)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.ket_noi)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.pin)
                                    </td>*@

                                    <td>
                                        @Html.DisplayFor(modelItem => item.moi)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.style)
                                    </td>
                                    
                                    <td>
                                        @Html.ActionLink("Edit", "Edit", new { id = item.sanpham_id })
                                        @Html.ActionLink("Details", "Details", new { id = item.sanpham_id })
                                        @Html.ActionLink("Delete", "Delete", new { id = item.sanpham_id })
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <!-- /.table-responsive -->

            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>

<style>
    a {
        color: red;
        /*font-size:16px;*/
    }

        a:hover {
            color: blue;
        }
</style>

Web_DienThoaiDiDong_1/Web_DienThoaiDiDong_1/MvcApplication8/Areas/Admin/Views/Quanlisanpham/Themmoi.cshtml
@model MvcApplication8.Models.sanpham

@{
    ViewBag.Title = "Themmoi";
    Layout = "~/Areas/Admin/Views/Layout/LayoutAdmin.cshtml";
}

<h2>Thêm mới sản phẩm</h2>
@* Thêm thuộc tính  *@
@using (Html.BeginForm("Themmoi", "Quanlisanpham", FormMethod.Post, new { enctype = "multipart/form-data", role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        @*<legend>sanpham</legend>*@

        <div class="editor-label">
            @Html.LabelFor(model => model.sanpham_name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.sanpham_name)
            @Html.ValidationMessageFor(model => model.sanpham_name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.gia_sanpham)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.gia_sanpham)
            @Html.ValidationMessageFor(model => model.gia_sanpham)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.soluong_sp)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.soluong_sp)
            @Html.ValidationMessageFor(model => model.soluong_sp)
            @* Kiểm tra rỗng *@
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.theloai_id)
        </div>
        <div class="editor-field">
            @Html.DropDownList("theloai_id") @*trùng tên ViewBag*@
        </div>


        <div class="editor-label">
            @Html.LabelFor(model => model.hinhanh_sp)
        </div>
        <div class="editor-field" >
            @*name trùng với tên với tham số bên controler*@
            <input  type="file" name="UrlAnh" />
            @* Thông báo trùng *@
            @ViewBag.Thongbao
        </div>

        @*<div class="editor-label">
            @Html.LabelFor(model => model.hinhanh_sp1)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.hinhanh_sp1)
            @Html.ValidationMessageFor(model => model.hinhanh_sp1)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.hinhanh_sp3)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.hinhanh_sp3)
            @Html.ValidationMessageFor(model => model.hinhanh_sp3)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.hinhanh_sp4)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.hinhanh_sp4)
            @Html.ValidationMessageFor(model => model.hinhanh_sp4)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.kichthuoc_hinhanh)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.kichthuoc_hinhanh)
            @Html.ValidationMessageFor(model => model.kichthuoc_hinhanh)
        </div> *@
        <div class="editor-label">
            @Html.LabelFor(model => model.camera_truoc)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.camera_truoc)
            @Html.ValidationMessageFor(model => model.camera_truoc)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.camera_sau)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.camera_sau)
            @Html.ValidationMessageFor(model => model.camera_sau)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.he_dieu_hanh)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.he_dieu_hanh)
            @Html.ValidationMessageFor(model => model.he_dieu_hanh)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.cpu)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.cpu)
            @Html.ValidationMessageFor(model => model.cpu)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ram)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ram)
            @Html.ValidationMessageFor(model => model.ram)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.bo_nho_trong)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.bo_nho_trong)
            @Html.ValidationMessageFor(model => model.bo_nho_trong)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.the_nho)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.the_nho)
            @Html.ValidationMessageFor(model => model.the_nho)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.sim)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.sim)
            @Html.ValidationMessageFor(model => model.sim)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ket_noi)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ket_noi)
            @Html.ValidationMessageFor(model => model.ket_noi)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.pin)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.pin)
            @Html.ValidationMessageFor(model => model.pin)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.moi)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.moi)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.style)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.style)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.chuthich)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.chuthich)
            @Html.ValidationMessageFor(model => model.chuthich)
        </div>
        <p>
            <br />
            <input style="color:blue" type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@*@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}*@

<style>
    input[type=text] {
        width: 343px;
    }
    
</style>